### ISSUE TITLE
Error: 524: Origin Time-out

### ISSUE THREAD

**Issue by hsjo12** [web3-storage/ipfs-car#108]
Hello, 

I tweaked the example code (https://docs.web3.storage/) to put files on IPFS. 
```
const storage = new Web3Storage({ token })
const files = [];
for(let i = 1; i<1003; i++){`
    const pathFiles = await getFilesFromPath(`D:/jsonFolder/${i}.json`);
  files.push(...pathFiles);
}

console.log(`Uploading ${files.length} files`)
const cid = await storage.put(files);
console.log('Content added with CID:', cid)
```

It returns

Error: 524: Origin Time-out
    at pRetry.retries (file:///D:/node_modules/web3.storage/src/lib.js:155:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RetryOperation._fn (D:\node_modules\p-retry\index.js:50:12) {
  attemptNumber: 6,
  retriesLeft: 0
}

I do not know why I got this error, it was ok with 500 files . 

Please give me some advice

**Comment by vasco-santos** [comment]
Hey @hsjo12 
The error is not related to `ipfs-car` itself, given it was sent into the service which received a timeout from the API.
Can you provide us more information about the files you are trying to add?

**Comment by dchoi27** [comment]
Closing for now, please reopen if you are still having issues!
