### ISSUE TITLE
CAR and SPLITTING seems fine, but uploading to nft.storage isn't liking it.

### ISSUE THREAD

**Issue by lloydcarroll** [web3-storage/ipfs-car#118]
I posted on discord too but no response yet. I'm hoping someone here can help as well. So, I created the CAR file and I can list contents and recognizes everything. I also used the split with no problems and seems fine. Problem is, when I upload to NFT.STORAGE. I can upload FILE-0.CAR file fine (first one). But, I get Error Uploading: Missing block for alskj23k4023nklsjfa whatever. The file is there, but has error pinning and gives that error. I thought it was because the other files are not there yet, but it will NOT let me upload any other files. They error out as soon as I press the upload button. So, I'm thinking I'm missing something in the process.

**Comment by lloydcarroll** [comment]
I did not. In fact, I've been trying to use the http api at nft.storage and I just get 404 error.  I will try the js client and see.

**Comment by dchoi27** [comment]
Closing this - user figured things out in other issues they opened

**Comment by lloydcarroll** [comment]
Hey sorry. The Meta uploaded finally but I still have one image folder that
has the same error. If I give you the CID, would that help?
