### ISSUE TITLE
complete example for `packToBlob`

### ISSUE THREAD

**Issue by dadaphl** [web3-storage/ipfs-car#121]
the example for the README explains usage of `packToBlob` as follows:

```
import { packToBlob } from 'ipfs-car/pack/blob'
import { MemoryBlockStore } from 'ipfs-car/blockstore/memory' // You can also use the `level-blockstore` module

const { root, car } = await packToBlob({
  input: [new Uint8Array([21, 31, 41])],
  blockstore: new MemoryBlockStore()
})
```

Unfortunately I can not use this example to generate a valid car file. I specifically struggle with the `input` param.
It would be helpful to provide a more comprehensive example here to show how the input data shall be provided. The README says the input should be a `ImportCandidateStream` and links to  `utils.ts` but I don't understand how to construct a `ImportCandidateStream` from this. Maybe it's obvious and I'm missing something here.

Thank you so much in advance.

**Comment by vasco-santos** [comment]
Probably we should have an examples folder with some possibilities. This library works in Node and Browser in multiple ways, that's the main reason for having low level docs and example.
