### ISSUE TITLE
Add support for building --trickle tree

### ISSUE THREAD

**Issue by hsn10** [web3-storage/ipfs-car#137]
Last go-ipfs option missing for making CAR is --trickle

**Comment by vasco-santos** [comment]
Hi @hsn10 

This should be quite easy to add as an option. `ipfs-car` relies on unixfs importer, which currently supports trickle strategy https://github.com/ipfs/js-ipfs-unixfs/blob/master/packages/ipfs-unixfs-importer/src/options.js#L28 

ipfs-car pack functions should be able to receive strategy and pass it to unixfs importer. Each pack function like https://github.com/web3-storage/ipfs-car/blob/main/src/pack/index.ts#L42 should be updated to support it.

@hsn10 would you be willing to PR and add it?

**Comment by heyjay44** [comment]
Closing this issue since we haven't had a response in 30 days. @hsn10, please reach out if you want to continue the conversation.
