### ISSUE TITLE
Tried packing files using ipfs-car and got folling error, pls help!!

### ISSUE THREAD

**Issue by Abhay-2811** [web3-storage/ipfs-car#150]
<img width="869" alt="Screenshot 2023-03-22 at 11 59 03 AM" src="https://user-images.githubusercontent.com/97840499/226820153-fe111904-8a17-4f99-b6db-47c86a6d8fe4.png">

**Comment by vasco-santos** [comment]
Hi @Abhay-2811 
It looks like you are using older version of `node.js`. You can see support for TransformStream in https://developer.mozilla.org/en-US/docs/Web/API/TransformStream#browser_compatibility and therefore this package required Node 18+ per https://github.com/web3-storage/ipfs-car/blob/main/package.json#L61

**Comment by Abhay-2811** [comment]
Thanks for the response, i upgraded the node version and it worked.
A new doubt btw 
`TypeError [ERR_INVALID_ARG_TYPE]: The "transform.writable" property must be an instance of WritableStream. Received type string ('./b.car')`

**Comment by vasco-santos** [comment]
Hi @Abhay-2811 
Could we get access to the CAR file you trying to unpack?

It can be possible that reader.get returns undefined. I could get a packed CAR working fine with:

```js
import { CarIndexedReader } from '@ipld/car/indexed-reader'
import { recursive as exporter } from 'ipfs-unixfs-exporter'

const reader = await CarIndexedReader.fromFile('./a.car')
const roots = await reader.getRoots()

// @ts-ignore
const entries = exporter(roots[0], {
  async get (cid) {
    const block = await reader.get(cid)
    return block?.bytes
  }
})

for await (const entry of entries) {
  if (entry.type === 'file' || entry.type === 'raw') {
    console.log('file', entry.path, entry.content)
  } else if (entry.type === 'directory') {
    console.log('directory', entry.path)
  }
}

```

**Comment by vasco-santos** [comment]
Hi @Abhay-2811 
Could we get access to the CAR file you trying to unpack?

It can be possible that reader.get returns undefined. I could get a packed CAR working fine with:

```js
import { CarIndexedReader } from '@ipld/car/indexed-reader'
import { recursive as exporter } from 'ipfs-unixfs-exporter'

const reader = await CarIndexedReader.fromFile('./a.car')
const roots = await reader.getRoots()

// @ts-ignore
const entries = exporter(roots[0], {
  async get (cid) {
    const block = await reader.get(cid)
    return block?.bytes
  }
})

for await (const entry of entries) {
  if (entry.type === 'file' || entry.type === 'raw') {
    console.log('file', entry.path, entry.content)
  } else if (entry.type === 'directory') {
    console.log('directory', entry.path)
  }
}

```
