### ISSUE TITLE
Example from README "fetch and locally verify file..." fails

### ISSUE THREAD

**Issue by meandavejustice** [web3-storage/ipfs-car#152]
Example reads:

Fetch and locally verify files from a IPFS gateway over http

``` 
curl "https://ipfs.io/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu?format=car" | ipfs-car unpack
```

Error: 🔴 
`Not a file - specify output path with --output`

![image](https://user-images.githubusercontent.com/1844554/235783258-78701c01-ac5f-4455-a0ad-8bc2290baae5.png)

**Comment by alanshaw** [comment]
Ah because that CID is a directory it cannot be printed to terminal so you need to use `--output` to specify a directory to unpack into. Thanks - will fix.
