### ISSUE TITLE
Directories containing only directories are removed from path (different from go-car)

### ISSUE THREAD

**Issue by wackazong** [web3-storage/ipfs-car#160]
If I pack a file in a nested directory the intermediate directory is removed from the .car file. This is in contradiction to how go-car behaves.

```console
mkdir -p root/intermediate
echo "hello world" > root/intermediate/test.txt
ipfs-car pack root -o result.car
```

Looking at the .car file it does not contain the `intermediate` directory but it immediately contains the file. 

<img width="1019" alt="image" src="https://github.com/web3-storage/ipfs-car/assets/67227/330d9a0c-9da0-49d2-b4e2-69acad9ad020">

The problem lies with the files-from-paths package which removes a common path as stated in the [usage description](https://www.npmjs.com/package/files-from-path).

```
// Output:
// [
//   { name: 'file.txt', stream: [Function: stream] },
//   { name: 'dir/b.pdf', stream: [Function: stream] },
//   { name: 'dir/images/cat.gif', stream: [Function: stream] },
// ]
// Note: common sub-path ("path/to/") is removed.
```

**Comment by alanshaw** [comment]
This is the intended behaviour. Superflous paths in the DAG slows down access times because you have to download intermediate blocks. Trimming the common sub path is consistent with file picker dialogs on the web.
