### ISSUE TITLE
Keep seeing invalid bin warnings

### ISSUE THREAD

**Issue by Gozala** [web3-storage/ipfs-car#65]
I keep seeing following in CI

```
warning ipfs-car@0.4.3: Invalid bin entry for "🚘" (in "ipfs-car").
```

**Comment by vasco-santos** [comment]
Oh, what is the environment? I think I never ran into it

cc @olizilla

**Comment by olizilla** [comment]
yeah, but i love it too much to let it go.

**Comment by Gozala** [comment]
Oh is that emoji ? 

> Oh, what is the environment? I think I never ran into it

**Comment by vasco-santos** [comment]
> Oh is that emoji ?

Yes, that is the emoji. It is a bit annoying the warning.
I am ok with removing this, @olizilla are you fine with me PRing ?

**Comment by olizilla** [comment]
PR `npm` to remove the warning. What is invalid about an emoji? It works as a bin entry.

**Comment by olizilla** [comment]
trolling / not trolling. I don't know why it's a problem and am curious if anyone knows.

**Comment by Gozala** [comment]
Closing it, we can reopen if we decide to do something about it.
